### ISSUE TITLE
Percona Postgresql Operator Helm Chart doesn't reference namespace in templates

### ISSUE THREAD

**Issue by dfry** [percona/percona-helm-charts#328] opened 2024-05-17 15:44 UTC
The Percona Helm Chart should follow the same pattern as the other operator helm charts regarding setting the namespace:

`namespace: {{ .Release.Namespace }} `

as is shown in the pxc operator example here:  https://github.com/percona/percona-helm-charts/blob/878d860ab641e628b48d39725444bd33b3dd6322/charts/pxc-operator/templates/deployment.yaml#L5C3-L5C38

By contrast the postgresql operator helm chart templates have no namespace reference, here is an example: https://github.com/percona/percona-helm-charts/blob/878d860ab641e628b48d39725444bd33b3dd6322/charts/pg-operator/templates/deployment.yaml#L3

This becomes an issue when installing via kustomize and should be changed in any case for the sake of consistency.

**Comment by tplavcic** [comment] 2024-05-29 07:32
Hi @dfry ! I have opened a ticket in our Jira about this here: https://perconadev.atlassian.net/browse/K8SPG-585
So we will address is no later then next operator release.

**Comment by dfry** [comment] 2024-05-29 10:07
Thanks @tplavcic ,

Another thing worth mentioning is that it seems that the logic within the helm templates regarding watching all namespaces seems to be not working.  When all namespaces are watched, the permissions granted via k8s RBAC don't work correctly.  I can open another issue if you want.  But is seems that the other Percona operator charts function fine in this regard, so maybe following the same pattern across all the charts would be the best strategy.

Cheers

**Comment by tplavcic** [comment] 2024-05-29 10:50
Thanks for info! I will check it out and open a ticket for it since I don't want to mix two things here. Yes, we do try to have it consistent between all operators, but PG is a bit different so need to check it out, but if there's a bug it needs to be fixed anyway.

**Comment by tplavcic** [comment] 2024-05-29 11:39
@dfry , can you be more specific about `When all namespaces are watched, the permissions granted via k8s RBAC don't work correctly` - because I just tried it and it seems to work for me and I don't see some issues.
So I'm wondering what am I missing? I just set `watchAllNamespaces: true` and didn't change anything else, deployed operator in one namespace and PG cluster in another.

**Comment by tplavcic** [comment] 2024-05-29 13:44
I have merged the fix for adding namespace reference to the templates so it is available now in the newest versions of the charts.
I will close this issue, but since I cannot currently reproduce the issue with cluster wide role please open a new one and try to provide some info about what exactly is wrong.
Thank you for valuable feedback!

**Closed** 2024-05-29 13:44 UTC

**Comment by dfry** [comment] 2024-05-30 09:23
thanks @tplavcic , I will reproduce the issue on my side and open another issue with some logs/configs.
